const GO_BLACK_COLOR = 1;
const GO_BOARD_AREA = 81;
const GO_BOARD_SIZE = 9;
const GO_CURRENT_PLAYER_FEATURE_INDEX = 0;
const GO_CURRENT_PLAYER_ONE_LIBERTY_FEATURE_INDEX = 2;
const GO_CURRENT_PLAYER_TWO_LIBERTY_FEATURE_INDEX = 4;
const GO_EMPTY_COLOR = 0;
const GO_GAME_OVER_PASS_COUNT = 2;
const GO_KO_FEATURE_INDEX = 6;
const GO_KOMI_NORMALIZATION_POINTS = 15;
const GO_KOMI_FEATURE_INDEX = 11;
const GO_KOMI_POINTS = 7;
const GO_MAXIMUM_MOVE_COUNT = 120;
const GO_MINIMUM_PASS_MOVE_COUNT = 20;
const GO_NO_KO_MOVE = -1;
const GO_OPPONENT_FEATURE_INDEX = 1;
const GO_OPPONENT_ONE_LIBERTY_FEATURE_INDEX = 3;
const GO_OPPONENT_TWO_LIBERTY_FEATURE_INDEX = 5;
const GO_PASS_ALIVE_MAXIMUM_INTERNAL_POINT_COUNT = 1;
const GO_PASS_ALIVE_REQUIRED_VITAL_REGION_COUNT = 2;
const GO_PASS_FEATURE_INDEX_OFFSET = 8;
const GO_PASS_MOVE = 81;
const GO_RECENT_MOVE_FEATURE_INDEXES = [7, 8];
const GO_STUDENT_INPUT_PLANE_COUNT = 12;
const GO_WHITE_COLOR = -1;
const GO_MODEL_KERNEL_RADIUS = 1;
const GO_MODEL_KERNEL_SIZE = 3;
const GO_MODEL_POLICY_KERNEL_SIZE = 1;
const GO_MODEL_VALUE_KERNEL_SIZE = 1;
const GO_MODEL_VERSION = 1;

export {
  GO_BLACK_COLOR,
  GO_BOARD_AREA,
  GO_BOARD_SIZE,
  GO_CURRENT_PLAYER_FEATURE_INDEX,
  GO_CURRENT_PLAYER_ONE_LIBERTY_FEATURE_INDEX,
  GO_CURRENT_PLAYER_TWO_LIBERTY_FEATURE_INDEX,
  GO_EMPTY_COLOR,
  GO_GAME_OVER_PASS_COUNT,
  GO_KO_FEATURE_INDEX,
  GO_KOMI_FEATURE_INDEX,
  GO_KOMI_NORMALIZATION_POINTS,
  GO_KOMI_POINTS,
  GO_MAXIMUM_MOVE_COUNT,
  GO_MINIMUM_PASS_MOVE_COUNT,
  GO_MODEL_KERNEL_RADIUS,
  GO_MODEL_KERNEL_SIZE,
  GO_MODEL_POLICY_KERNEL_SIZE,
  GO_MODEL_VALUE_KERNEL_SIZE,
  GO_MODEL_VERSION,
  GO_NO_KO_MOVE,
  GO_OPPONENT_FEATURE_INDEX,
  GO_OPPONENT_ONE_LIBERTY_FEATURE_INDEX,
  GO_OPPONENT_TWO_LIBERTY_FEATURE_INDEX,
  GO_PASS_ALIVE_MAXIMUM_INTERNAL_POINT_COUNT,
  GO_PASS_ALIVE_REQUIRED_VITAL_REGION_COUNT,
  GO_PASS_FEATURE_INDEX_OFFSET,
  GO_PASS_MOVE,
  GO_RECENT_MOVE_FEATURE_INDEXES,
  GO_STUDENT_INPUT_PLANE_COUNT,
  GO_WHITE_COLOR,
};
