const GO_MODEL_KERNEL_SIZE = 3;
const GO_MODEL_KERNEL_RADIUS = 1;
const GO_MODEL_INT4_FORMAT = "million-go-int4";
const GO_MODEL_INT4_NIBBLE_BITS = 4;
const GO_MODEL_INT4_NIBBLE_MASK = 0xf;
const GO_MODEL_INT4_VALUES_PER_BYTE = 2;
const GO_MODEL_INT4_ZERO_POINT = 8;
const GO_MODEL_INT8_FORMAT = "million-go-int8";
const GO_MODEL_NESTED_RESIDUAL_BLOCK_KIND = "nested-bottleneck";
const GO_MODEL_POLICY_KERNEL_SIZE = 1;
const GO_MODEL_STANDARD_RESIDUAL_BLOCK_KIND = "standard";
const GO_MODEL_VALUE_KERNEL_SIZE = 1;
const GO_MODEL_VERSION = 1;

export {
  GO_MODEL_KERNEL_RADIUS,
  GO_MODEL_KERNEL_SIZE,
  GO_MODEL_INT4_FORMAT,
  GO_MODEL_INT4_NIBBLE_BITS,
  GO_MODEL_INT4_NIBBLE_MASK,
  GO_MODEL_INT4_VALUES_PER_BYTE,
  GO_MODEL_INT4_ZERO_POINT,
  GO_MODEL_INT8_FORMAT,
  GO_MODEL_NESTED_RESIDUAL_BLOCK_KIND,
  GO_MODEL_POLICY_KERNEL_SIZE,
  GO_MODEL_STANDARD_RESIDUAL_BLOCK_KIND,
  GO_MODEL_VALUE_KERNEL_SIZE,
  GO_MODEL_VERSION,
};
