const GO_MODEL_KERNEL_SIZE = 3;
const GO_MODEL_KERNEL_RADIUS = 1;
const GO_MODEL_POLICY_KERNEL_SIZE = 1;
const GO_MODEL_VALUE_KERNEL_SIZE = 1;
const GO_MODEL_VERSION = 1;

export {
  GO_MODEL_KERNEL_RADIUS,
  GO_MODEL_KERNEL_SIZE,
  GO_MODEL_POLICY_KERNEL_SIZE,
  GO_MODEL_VALUE_KERNEL_SIZE,
  GO_MODEL_VERSION,
};
